config/routes.rb
Rails.application.routes.draw do
  resources :variables
  resources :people
  resources :studies
  root to: 'studies#index'
end

app/models/person.rb
class Person < ApplicationRecord
  belongs_to :study
  has_many :evaluations
  accepts_nested_attributes_for :evaluations
  has_and_belongs_to_many :clusters

  def evaluation_for(variable)
    evaluations.where(variable: variable).first_or_create
  end

  def value_for(variable)
    evaluation_for(variable).value
  end

  def no_value_for?(variable)
    evaluation_for(variable).no_value?
  end

  def persons_close_on(variable)
    persons = []
    value = value_for(variable)
    return persons if value.nil?
    study.persons.where.not(id: id).each do |p|
      other_value = p.value_for(variable)
      next if other_value.nil?
      distance = (value - other_value).abs
      persons << p if distance < Cluster::THRESHOLD
    end
    persons
  end

  def create_evaluations
    study.variables.each do |variable|
      Evaluation.where(person: self, variable: variable).first_or_create
    end
  end

  def affinity_with(person)
    return 0 if person == self
    affinity = 0
    study.variables.each do |variable|
      variable.clusters.each do |cluster|
        if self.in?(cluster.persons)
          if person.in?(cluster.persons)
            affinity += 1
            break
          end
        end
      end
    end
    affinity
  end

  def affinity_with_others
    unless @affinity_with_others
      @affinity_with_others = 0
      study.persons.each do |person|
        @affinity_with_others += affinity_with(person)
      end
    end
    @affinity_with_others
  end

  def to_s
    "U#{code}"
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]
  before_action :set_study

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
    add_breadcrumb @study, @study
    add_breadcrumb 'Personnes'
    add_breadcrumb @person
  end

  # GET /people/new
  def new
    @person = Person.new
    @person.study = @study
    add_breadcrumb @study, @study
    add_breadcrumb 'Personnes'
    add_breadcrumb 'Nouvelle personne'
  end

  # GET /people/1/edit
  def edit
    @person.create_evaluations
    add_breadcrumb @study, @study
    add_breadcrumb 'Personnes'
    add_breadcrumb @person, @person
    add_breadcrumb 'Modifier'
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_study
      @study = Study.find(params[:study_id]) if params.has_key? :study_id
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
      @study = @person.study
    end

    # Only allow a list of trusted parameters through.
    def person_params
      params.require(:person).permit(:study_id, :code, evaluations_attributes: [:id, :value, :no_value])
    end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<%= simple_form_for person do |f| %>
  <%= f.association :study, as: :hidden %>
  <%= f.input :code %>
  <h2>Evaluations</h2>
  <table class="table">
    <%= f.simple_fields_for :evaluations do |e| %>
      <tr>
        <td width="300"><%= e.object.variable %></td>
        <td>
          <div class="value_and_no_value">
            <%= e.input :no_value, as: :boolean %>
            <%= e.input :value,
                        as: :range,
                        label: false,
                        html: {
                          style: 'width: 100%'
                        } %>
          </div>
        </td>
      </tr>
    <% end %>
  </table>
  <%= f.submit 'Enregistrer', class: 'btn btn-primary btn-sm' %>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form', person: @person %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>People</h1>

<table>
  <thead>
    <tr>
      <th>Study</th>
      <th>Code</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.study %></td>
        <td><%= person.code %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form', person: @person %>

app/views/people/show.html.erb
<h1><%= @person %></h1>

<%= link_to 'Edit', edit_person_path(@person), class: 'btn btn-primary btn-sm' %>

<h2>Variables</h2>
<table class="table">
  <% @person.study.variables.each do |variable| %>
    <% evaluation = @person.evaluation_for(variable) %>
    <tr>
      <td><%= link_to variable, variable %></td>
      <td><%= render 'evaluations/show', evaluation: evaluation %></td>
    </tr>
  <% end %>
</table>