config/routes.rb
Rails.application.routes.draw do
  resources :variables
  resources :people
  resources :studies
  root to: 'studies#index'
end

app/models/study.rb
class Study < ApplicationRecord
  has_many :persons
  has_many :variables

  def build_clusters
    variables.find_each &:build_clusters
  end

  def to_s
    "#{name}"
  end
end

app/controllers/studies_controller.rb
class StudiesController < ApplicationController
  before_action :set_study, only: [:show, :edit, :update, :destroy]

  # GET /studies
  # GET /studies.json
  def index
    @studies = Study.all
  end

  # GET /studies/1
  # GET /studies/1.json
  def show
    @study.build_clusters
    add_breadcrumb @study
  end

  # GET /studies/new
  def new
    @study = Study.new
  end

  # GET /studies/1/edit
  def edit
  end

  # POST /studies
  # POST /studies.json
  def create
    @study = Study.new(study_params)

    respond_to do |format|
      if @study.save
        format.html { redirect_to @study, notice: 'Study was successfully created.' }
        format.json { render :show, status: :created, location: @study }
      else
        format.html { render :new }
        format.json { render json: @study.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /studies/1
  # PATCH/PUT /studies/1.json
  def update
    respond_to do |format|
      if @study.update(study_params)
        format.html { redirect_to @study, notice: 'Study was successfully updated.' }
        format.json { render :show, status: :ok, location: @study }
      else
        format.html { render :edit }
        format.json { render json: @study.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /studies/1
  # DELETE /studies/1.json
  def destroy
    @study.destroy
    respond_to do |format|
      format.html { redirect_to studies_url, notice: 'Study was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_study
      @study = Study.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def study_params
      params.require(:study).permit(:name)
    end
end

app/helpers/studies_helper.rb
module StudiesHelper
end

app/views/studies/_form.html.erb
<%= simple_form_for study do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>

app/views/studies/edit.html.erb
<h1>Editing Study</h1>

<%= render 'form', study: @study %>

<%= link_to 'Show', @study %> |
<%= link_to 'Back', studies_path %>

app/views/studies/index.html.erb
<h1>Studies</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @studies.each do |study| %>
      <tr>
        <td><%= link_to study, study %></td>
        <td>
          <%= link_to 'Edit', edit_study_path(study) %>
          <%= link_to 'Destroy', study, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Study', new_study_path, class: 'btn btn-primary btn-sm' %>

app/views/studies/new.html.erb
<h1>New Study</h1>

<%= render 'form', study: @study %>

<%= link_to 'Back', studies_path %>

app/views/studies/show.html.erb
<h1><%= @study.name %></h1>
<%= link_to 'Edit', edit_study_path(@study), class: 'btn btn-primary btn-sm' %>

<h2 class="mt-5">Utilisateurs</h2>
<ul class="list-unstyled">
  <% @study.persons.each do |person| %>
    <li><%= link_to person, person %></li>
  <% end %>
</ul>
<%= link_to 'New Person', new_person_path(study_id: @study.id), class: 'btn btn-primary btn-sm' %>

<h2 class="mt-5">Variables</h2>
<table class="table">
  <thead>
    <tr>
      <th>Variable</th>
      <th>Clusters</th>
    </tr>
  </thead>
  <% @study.variables.each do |variable| %>
    <tr>
      <td><%= link_to variable, variable %></td>
      <td>
        <% variable.clusters.each do |cluster| %>
          <span class="badge badge-primary"><%= cluster %></span>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>
<%= link_to 'New Variable', new_variable_path(study_id: @study.id), class: 'btn btn-primary btn-sm' %>

<h2 class="mt-5">Affinité des profils</h2>
<p>1 point par cluster en commun (limité à un cluster commun par variable).</p>
<table class="table table-bordered">
  <thead>
    <tr>
      <th></th>
      <% @study.persons.each do |person| %>
        <th><%= person %></th>
      <% end %>
      <th>Total</th>
    </tr>
  </thead>
  <tbody>
    <% @study.persons.each do |person| %>
      <tr>
        <td><%= person %></td>
        <% @study.persons.each do |p| %>
          <td><%= person.affinity_with(p) %></td>
        <% end %>
        <td><%= person.affinity_with_others %></td>
      </tr>
    <% end %>
    <tr>
      <td>Total</td>
      <% @study.persons.each do |p| %>
        <td><%= p.affinity_with_others %></td>
      <% end %>
      <td></td>
    </tr>
  </tbody>
</table>