config/routes.rb
Rails.application.routes.draw do
  resources :variables
  resources :people
  resources :studies
  root to: 'studies#index'
end

app/models/variable.rb
class Variable < ApplicationRecord
  belongs_to :study
  has_many :evaluations
  accepts_nested_attributes_for :evaluations
  has_many :clusters

  def build_clusters
    clean_clusters!
    study.persons.each do |p|
      next if p.no_value_for?(self)
      others = p.persons_close_on(self)
      persons = [p].concat others
      Cluster.build(self, persons)
    end
  end

  def to_s
    "#{name}"
  end

  protected

  def clean_clusters!
    clusters.destroy_all
  end
end

app/controllers/variables_controller.rb
class VariablesController < ApplicationController
  before_action :set_variable, only: [:show, :edit, :update, :destroy]
  before_action :set_study

  # GET /variables
  # GET /variables.json
  def index
    @variables = Variable.all
  end

  # GET /variables/1
  # GET /variables/1.json
  def show
    @variable.build_clusters
    add_breadcrumb @study, @study
    add_breadcrumb 'Variables'
    add_breadcrumb @variable
  end

  # GET /variables/new
  def new
    @variable = Variable.new
    @variable.study_id = params[:study_id]
    add_breadcrumb @study, @study
    add_breadcrumb 'Variables'
    add_breadcrumb 'Nouvelle variable'
  end

  # GET /variables/1/edit
  def edit
  end

  # POST /variables
  # POST /variables.json
  def create
    @variable = Variable.new(variable_params)

    respond_to do |format|
      if @variable.save
        format.html { redirect_to @variable.study, notice: 'Variable was successfully created.' }
        format.json { render :show, status: :created, location: @variable }
      else
        format.html { render :new }
        format.json { render json: @variable.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /variables/1
  # PATCH/PUT /variables/1.json
  def update
    respond_to do |format|
      if @variable.update(variable_params)
        format.html { redirect_to @variable.study, notice: 'Variable was successfully updated.' }
        format.json { render :show, status: :ok, location: @variable }
      else
        format.html { render :edit }
        format.json { render json: @variable.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /variables/1
  # DELETE /variables/1.json
  def destroy
    @variable.destroy
    respond_to do |format|
      format.html { redirect_to variables_url, notice: 'Variable was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_study
      @study = Study.find(params[:study_id]) if params.has_key? :study_id
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_variable
      @variable = Variable.find(params[:id])
      @study = @variable.study
    end

    # Only allow a list of trusted parameters through.
    def variable_params
      params.require(:variable).permit(:name, :study_id)
    end
end

app/helpers/variables_helper.rb
module VariablesHelper
end

app/views/variables/_form.html.erb
<%= simple_form_for variable do |f| %>
  <%= f.association :study, as: :hidden %>
  <%= f.input :name %>
  <%= f.submit 'Enregistrer', class: 'btn btn-primary btn-sm' %>
<% end %>

app/views/variables/edit.html.erb
<h1>Editing Variable</h1>

<%= render 'form', variable: @variable %>

app/views/variables/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Variables</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Study</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @variables.each do |variable| %>
      <tr>
        <td><%= variable.name %></td>
        <td><%= variable.study %></td>
        <td><%= link_to 'Show', variable %></td>
        <td><%= link_to 'Edit', edit_variable_path(variable) %></td>
        <td><%= link_to 'Destroy', variable, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Variable', new_variable_path %>

app/views/variables/new.html.erb
<h1>New Variable</h1>

<%= render 'form', variable: @variable %>

app/views/variables/show.html.erb
<h1><%= @variable %></h1>

<%= link_to 'Edit', edit_variable_path(@variable), class: 'btn btn-primary btn-sm' %>

<h2 class="mt-5">Utilisateurs</h2>
<table class="table">
  <thead>
    <tr>
      <th>Utilisateur</th>
      <th>Proche de...</th>
      <th>Valeur</th>
    </tr>
  </thead>
  <% @study.persons.each do |person| %>
    <% evaluation = person.evaluation_for(@variable) %>
    <tr>
      <td><%= link_to person, person %></td>
      <td>
        <% person.persons_close_on(@variable).each do |p| %>
          <%= p %>
        <% end %>
      </td>
      <td><%= render 'evaluations/show', evaluation: evaluation %></td>
    </tr>
  <% end %>
</table>

<h2 class="mt-5">Clusters</h2>
<table class="table">
  <% @variable.clusters.reload.each do |cluster| %>
    <tr>
      <td><%= cluster %></td>
    </tr>
  <% end %>
</table>